### ISSUE TITLE
TypeError: unsupported operand

### ISSUE THREAD

**Issue by Tux-Panik** [hegusung/AVSignSeek#2]
Hello,
I made an exercice today to test this interesting tool, but I reached the following error:

**Command:**
`python3 /opt/AVSignSeek/avsignseek.py -f sample.exe -p infected /media/sf_ANALYSIS/DIODE/test.zip`

**Output:**
`Traceback (most recent call last):`
`  File "/opt/AVSignSeek/avsignseek.py", line 46, in <module>`
`    main(args)`
`  File "/opt/AVSignSeek/avsignseek.py", line 28, in main`
`    print_results(file_bin, signature_range_list, args.output_file)`
`  File "/opt/AVSignSeek/result.py", line 20, in print_results`
`    output_line =  b"".join([b"%.2x " % c for c in row]).decode().ljust(60)`
`  File "/opt/AVSignSeek/result.py", line 20, in <listcomp>`
`    output_line =  b"".join([b"%.2x " % c for c in row]).decode().ljust(60)`
`TypeError: unsupported operand type(s) for %: 'bytes' and 'int'`

If you have any idea about this issue.
Thanks in advance,

Regards,
Julien

**Comment by hegusung** [comment]
Hello,

Thank you for reporting this, apparently you are using python3.4 which does not support the '%' statement like in python3.6.

I just pushed a new commit to solve this compatibility issue, the code should now also work for python3.4. Please let me know if you encounter any other issues.

Regards,
Hegusung

**Comment by Tux-Panik** [comment]
Issue fix.
Thanks for fast answer.
Regards,
Julien
